### ISSUE TITLE
:checkhealth failed after upgrade module neovim to 0.3.1 (on python 3.7.1)

### ISSUE THREAD

**Issue by number5** [neovim/pynvim#366]
**Expected result**: `:checkhealth` all passed

**Actual result**:
```
## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
  - INFO: Executable: /usr/local/bin/python3
  - ERROR: Command error (job=7): `'/usr/local/bin/python3' -c 'import sys; sys.path.remove(""); import neovim; print(neovim.__file__)'` (in '/Users/bruce/work/encoding-service')
    Output: Traceback (most recent call last):  File "<string>", line 1, in <module>ModuleNotFoundError: No module named 'neovim'
  - INFO: Python3 version: 3.7.1
  - INFO: python3-neovim version: unable to load neovim Python module
  - ERROR: Neovim Python client is not installed.
    Error: unable to load neovim Python module
    - ADVICE:
      - Run in shell: pip3 install neovim 
```

**Steps to reproduce**:

1. `pip3 install neovim==0.3.1`
2. `pip3 show neovim`
   ```
   Name: neovim
   Version: 0.3.1
   Summary: Transition packgage for pynvim
   Home-page: http://github.com/neovim/python-client
   Author: Thiago de Arruda
   Author-email: tpadilha84@gmail.com
   License: Apache
   Location: /usr/local/lib/python3.7/site-packages
   Requires: pynvim
   Required-by:
   ```

3. `pip3 show pynvim`

```
Name: pynvim
Version: 0.3.1
Summary: Python client to neovim
Home-page: http://github.com/neovim/python-client
Author: Thiago de Arruda
Author-email: tpadilha84@gmail.com
License: Apache
Location: /usr/local/lib/python3.7/site-packages
Requires: msgpack, greenlet
Required-by: neovim
```

4. `nvim +checkhealth`

```

health#LanguageClient#check
========================================================================
  - OK: binary found: /Users/bruce/.config/nvim/plugged/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.127 229df982b764502c4e03b524ad3c14eb0db8e273

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - ERROR: Python provider error
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/local/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/local/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/local/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
  - INFO: Executable: /usr/local/bin/python3
  - ERROR: Command error (job=7): `'/usr/local/bin/python3' -c 'import sys; sys.path.remove(""); import neovim; print(neovim.__file__)'` (in '/Users/bruce/work/encoding-service')
    Output: Traceback (most recent call last):  File "<string>", line 1, in <module>ModuleNotFoundError: No module named 'neovim'
  - INFO: Python3 version: 3.7.1
  - INFO: python3-neovim version: unable to load neovim Python module
  - ERROR: Neovim Python client is not installed.
    Error: unable to load neovim Python module
    - ADVICE:
      - Run in shell: pip3 install neovim

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.7.1

## Node.js provider (optional)
  - INFO: Node.js: v11.2.0
  - INFO: Neovim node.js host: /usr/local/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.2.1
```

**Comment by mhinz** [comment]
Yeah, that's a bit unfortunate. After just upgrading the package, `import neovim` won't work anymore, but that's used by `:checkhealth` to check if there's any supported Python interpreter that can access that module.

Please read this: https://github.com/neovim/neovim/wiki/Following-HEAD#20181118

Removing `pynvim` and `neovim` and reinstalling `pynvim` afterwards should make `import neovim` work again and resolves the `:checkhealth` issue.

**Comment by number5** [comment]
Following the steps in docs like:
```
pip3 uninstall neovim
pip3 uninstall pynvim
pip3 install pynvim
```
fixed it.

It would be good if the error messages mentioned https://github.com/neovim/neovim/wiki/Following-HEAD#20181118 though.

**Comment by mhinz** [comment]
You didn't mention the Nvim version you're using, but master's `:checkhealth` is already checking for pynvim instead. It will be in the next release. :)

**Comment by number5** [comment]
Sorry forgot the most important one 😋, my Neovim version is 0.3.1

**Comment by daveyarwood** [comment]
I'm having related issues since upgrading Neovim, which it seems like is depending on the `pynvim` module now instead of the `neovim` module.

Even after uninstalling the `pynvim` and `neovim` modules and installing `pynvim` using both `pip` and `pip3`, the Python 2 provider seems unable to recognize `pynvim` as being installed:

(Note that the Python 3 provider seems to be working fine.)

```
## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/usr/bin/python"
  - INFO: Executable: /usr/bin/python
  - ERROR: Command error (job=9, exit code 1): `/usr/bin/python -c 'import sys; sys.path.remove(""); import pynvim; print(pynvim.__file__)'` (in '/home/dave/code/advent-of-code')
    Output: Traceback (most recent call last):  File "<string>", line 1, in <module>ImportError: No module named pynvim
    Stderr: Traceback (most recent call last):  File "<string>", line 1, in <module>ImportError: No module named pynvim
  - INFO: Python version: 2.7.12
  - INFO: pynvim version: unable to load pynvim Python module
  - ERROR: Importing "neovim" failed.
    - ADVICE:
      - Reinstall "pynvim" and optionally "neovim" packages.
          pip uninstall pynvim neovim
          pip install pynvim
          pip install neovim # only if needed by third-party software
  - ERROR: pynvim is not installed.
    Error: unable to load pynvim Python module
    - ADVICE:
      - Run in shell: pip install pynvim

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.5.2
  - INFO: pynvim version: 0.3.1
  - OK: Latest pynvim is installed.
```

It seems like Python 2 itself is unable to import pynvim, despite the fact that I installed it apparently successfully:

```
$ pip show pynvim
Name: pynvim
Version: 0.3.1
Summary: Python client to neovim
Home-page: http://github.com/neovim/python-client
Author: Thiago de Arruda
Author-email: tpadilha84@gmail.com
License: Apache
Location: /usr/local/lib/python3.5/dist-packages
Requires: greenlet, msgpack
Required-by:

$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import neovim
>>> import pynvim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pynvim
>>>
```

For comparison, note that I am able to import pynvim from python3:

```
$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import neovim
>>> import pynvim
>>>
```

I did notice that I do NOT have the `neovim` module installed anymore, yet I am able to `import neovim`, so could the issue be that the `pynvim` module is still named `neovim` in the sense that you have to do `import neovim` to import it? That might explain the `ImportError: No module named pynvim` error that happens when I run `:checkhealth` in Neovim.

**Comment by justinmk** [comment]
> $ pip show pynvim
> ...
> Location: /usr/local/lib/python3.5/dist-packages


@daveyarwood your `pip` is managing python 3.5, not python 2. Try `pip2` or figure out what "pip" tool on your system actually manages python 2 packages.

**Comment by daveyarwood** [comment]
@justinmk Nice catch -- that was indeed the problem! Using `pip2` to uninstall `pynvim` and `neovim` and then install `pynvim` did the trick.

**Comment by jaybocc2** [comment]
Can we at least reference this on the Readme? I had to dig a little more than was necessary to find out the package had been renamed.

**Comment by alexventuraio** [comment]
I got the same error in **MacOS Ventura 13.2.1 (22D68)** and I fixed it by running `/opt/homebrew/bin/python3 -m pip install pynvim` as suggested in the report:

<img width="3120" alt="Screenshot 2023-02-28 at 14 00 55" src="https://user-images.githubusercontent.com/13169164/221968117-0cfa8153-41e2-4792-816d-f76e3710df21.png">
