### ISSUE TITLE
vim.Function serialisation in `to_client`

### ISSUE THREAD

**Issue by rubdos** [neovim/pynvim#371]
My knowledge about vim internals is almost nothing, let alone my neovim knowledge. That being said...

I am using pynvim in combination with deoplete. I just filed https://github.com/Shougo/deoplete.nvim/issues/884, but it seems like it's not deoplete's fault. At a certain point, deoplete requests `vim_eval` of the global variable scope `g:`, and apparently I have a few function pointers in there.

This is an excerpt of the RPC server log:

```
2018-11-30 21:34:21,484 [INFO @ neovim_rpc_server.py:process_pending_requests:372] 15119 - get msg from channel [1]: [0, 39, 'nvim_eval', ['g:']]
2018-11-30 21:34:21,484 [INFO @ neovim_rpc_server.py:process_pending_requests:400] 15119 - sending result: [1, 39, None, <vim.dictionary object at 0x7f9b3cbc0b40>]
2018-11-30 21:34:21,484 [INFO @ neovim_rpc_protocol.py:handler:66] 15119 - serialising obj Function <vim.Function '2'>
2018-11-30 21:34:21,484 [INFO @ neovim_rpc_protocol.py:handler:66] 15119 - serialising obj Function <vim.Function '1'>
```

This is after I patched `neovim_rpc_protocol.py` to print whenever it's serialising an Function-typed variable (after line 65). If, instead of `return obj.name` I return an empty string `''`, deoplete works again :-)

So, I think the serialisation of `Function`s is incorrect, but I have no clue how it should be done.

For completeness sake, this is what happens normally:

```
Traceback (most recent call last):
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_server.py", line 400, in process_pending_requests
    packed = msgpack.packb(neovim_rpc_protocol.to_client(result))
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 66, in to_client
    return walk(handler, msg)
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 20, in walk
    return list(walk(fn, o) for o in obj)
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 20, in <genexpr>
    return list(walk(fn, o) for o in obj)
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 23, in walk
    obj.items())
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 22, in <genexpr>
    return dict((walk(fn, k), walk(fn, v)) for k, v in
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 20, in walk
    return list(walk(fn, o) for o in obj)
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 20, in <genexpr>
    return list(walk(fn, o) for o in obj)
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 24, in walk
    return fn(obj)
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 64, in handler
    return obj.name
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

Apparently, the function name contains a non-UTF-8 character? There's also a difference whether I use

```
logger.info("foo %s", obj.name) # prints "foo 1" in the log
logger.info("foo %s" % obj.name) # throws the same UTF-8 error about byte 0x80
```

Please let me know if more information is required.

**Comment by justinmk** [comment]
> Apparently, the function name contains a non-UTF-8 character

What's the function name?

**Comment by bfredl** [comment]
I take it you are using yarp+vim 8? Whenever something is decoded, `data.decode("utf-8", errors="surrogateescape")` should be used (and conversely for encoding). If yarp depends on builtin vim 8 functions (such as `funcobj.name`) that hardcodes incompatible behavior, arbitrary binary data cannot be supported. One could ask vim to start using surrogateescape (it does in some places, and I think I've already asked them to use it more), but there is not much that can be done on pynvim's end...

**Comment by rubdos** [comment]
> What's the function name?
If I had known, I would have told you. Whenever I try to access the `obj.name`, Python crashes on a UTF-8 error.

> I take it you are using yarp+vim 8?
Yes. And I sadly have only a vague clue about what all components do, but you seem to understand the issue without a lot of other details.

**Comment by rubdos** [comment]
> The issue is happening in this bridge https://github.com/roxma/vim-hug-neovim-rpc/blob/master/pythonx/neovim_rpc_protocol.py which is before pynvim sees the data. You could file this issue at https://github.com/roxma/vim-hug-neovim-rpc/ which might add a workaround, such as catching the exception and ignoring these names that cause trouble.

Seems like someone else discovered it there indeed: https://github.com/roxma/vim-hug-neovim-rpc/pull/45

Excuse me for misidentifying the repository of `neovim_rpc_protocol.py`. I should take more time reading these things.

Thank you for your help.
