### ISSUE TITLE
NvimError: Invalid Buffer Id

### ISSUE THREAD

**Issue by naftulikay** [neovim/pynvim#385]
I am on Ubuntu 18.04 (bionic) amd64. I have installed the NeoVim stable PPA.

Neovim version:

```
NVIM v0.3.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-M0l_b5/neovim-0.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-M0l_b5/neovim-0.3.1/build/config -I/build/neovim-M0l_b5/neovim-0.3.1/src -I/usr/include -I/build/neovim-M0l_b5/neovim-0.3.1/build/src/nvim/auto -I/build/neovim-M0l_b5/neovim-0.3.1/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

I'm using the Python `python-neovim` package provided by the repository:

**Comment by naftulikay** [comment]
My bad, didn't mean to open. Fix is likely to update the Python library from pip and not from apt.

**Comment by naftulikay** [comment]
Actually, still encountering this. I use [fzf](https://github.com/junegunn/fzf) for fuzzy-finding files and buffers. Often, when I attempt to switch buffers, I see the following exception:

```
error caught in async handler 'deoplete_on_event [{'rpc': 'deoplete_on_event', 'event': 'BufDelete', 'sources': []}]'
Traceback (most recent call last):
  File "/home/naftuli/.local/share/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 47, in on_event
    self._deoplete.on_event(context)
  File "/home/naftuli/.local/share/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 128, in on_event
    self._context._init_cached()
  File "/home/naftuli/.local/share/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/context.py", line 78, in _init_cached
    buftype = buffer.options['buftype']
  File "/home/naftuli/.local/lib/python3.6/site-packages/pynvim/api/common.py", line 88, in __getitem__
    return self._get(key)
  File "/home/naftuli/.local/lib/python3.6/site-packages/pynvim/api/common.py", line 51, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/home/naftuli/.local/lib/python3.6/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/naftuli/.local/lib/python3.6/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b'Invalid buffer id'
```

I have ensured that I'm running latest `pynvim` from PyPI and not the one provided by the distro.

**Comment by mhinz** [comment]
@shougo ^

**Comment by Shougo** [comment]
Hi.  Your deoplete is old.  Please use the latest version of deoplete.

**Comment by naftulikay** [comment]
This does seem to fix it, I had thought that my plugins had been updated. My bad.
