### ISSUE TITLE
E121: Undefined variable: b:after

### ISSUE THREAD

**Issue by purejoy** [neovim/pynvim#387]
neovim 0.3.3
pynvim 0.3.2
errors occurred while editing a CSS file.
[deoplete] Traceback (most recent call last):
  File "/home/ray/.local/share/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/source/omni.py", line 80, i
n gather_candidates
    candidates = self.vim.call(self._omnifunc, 0, '')
  File "/usr/lib64/python3.6/site-packages/pynvim/api/nvim.py", line 299, in call
    return self.request('nvim_call_function', name, args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b'Vim(if):E121: Undefined variable: b:after'
Error occurred calling omnifunction: csscomplete#CompleteCSS.  Use :messages / see above for error details.

**Comment by mhinz** [comment]
This is no issue with pynvim, it merely reports an error that happened within Nvim.

The last line says `Error occurred calling omnifunction: csscomplete#CompleteCSS` which hints at https://github.com/othree/csscomplete.vim although it doesn't use a variable `b:after`.

Find out which of your plugins is using such a variable, e.g.

```
$ grep -iR b:after ~/.config/nvim/plugged
```
