### ISSUE TITLE
python setup.py test failes on latest master and tag 0.3.2

### ISSUE THREAD

**Issue by doronbehar** [neovim/pynvim#394]
Hey,

Trying to build this module for a certain Linux distribution. I've encountered the errors below. To put aside distro specific issues, I've tested these against the latest master and tag 0.3.2  as described:

- I created a new virtual environment with `python -m venv venv`
- I activated it with `source venv/bin/activate`.
- I've verified that `which python` shows the environment's python.
- I ran `python setup.py test`.

And I got the following output:
<details><summary>(collapsed)</summary>

```
running test
Searching for greenlet
Reading https://pypi.org/simple/greenlet/
Downloading https://files.pythonhosted.org/packages/9d/ef/ac10aa1293f64939e4511909c570d969566126214af5dd7ba0afd353d88b/greenlet-0.4.15-cp37-cp37m-manylinux1_x86_64.whl#sha256=8041e2de00e745c0e05a502d6e6db310db7faa7c979b3a5877123548a4c0b214
Best match: greenlet 0.4.15
Processing greenlet-0.4.15-cp37-cp37m-manylinux1_x86_64.whl
Installing greenlet-0.4.15-cp37-cp37m-manylinux1_x86_64.whl to /var/code/doron/pynvim/.eggs

Installed /var/code/doron/pynvim/.eggs/greenlet-0.4.15-py3.7-linux-x86_64.egg
Searching for msgpack>=0.5.0
Reading https://pypi.org/simple/msgpack/
Downloading https://files.pythonhosted.org/packages/a8/7b/630049fc4af9e68a625738612edc264ce7cb586c5001a2d4d2209a4f61c1/msgpack-0.6.1-cp37-cp37m-manylinux1_x86_64.whl#sha256=7c55649965c35eb32c499d17dadfb8f53358b961582846e1bc06f66b9bccc556
Best match: msgpack 0.6.1
Processing msgpack-0.6.1-cp37-cp37m-manylinux1_x86_64.whl
Installing msgpack-0.6.1-cp37-cp37m-manylinux1_x86_64.whl to /var/code/doron/pynvim/.eggs

Installed /var/code/doron/pynvim/.eggs/msgpack-0.6.1-py3.7-linux-x86_64.egg
Searching for pytest>=3.4.0
Best match: pytest 4.5.0
Processing pytest-4.5.0-py3.7.egg

Using /var/code/doron/pynvim/.eggs/pytest-4.5.0-py3.7.egg
Searching for wcwidth
Reading https://pypi.org/simple/wcwidth/
Downloading https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl#sha256=f4ebe71925af7b40a864553f761ed559b43544f8f71746c2d756c7fe788ade7c
Best match: wcwidth 0.1.7
Processing wcwidth-0.1.7-py2.py3-none-any.whl
Installing wcwidth-0.1.7-py2.py3-none-any.whl to /var/code/doron/pynvim/.eggs

Installed /var/code/doron/pynvim/.eggs/wcwidth-0.1.7-py3.7.egg
Searching for six>=1.10.0
Reading https://pypi.org/simple/six/
Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl#sha256=3350809f0555b11f552448330d0b52d5f24c91a322ea4a15ef22629740f3761c
Best match: six 1.12.0
Processing six-1.12.0-py2.py3-none-any.whl
Installing six-1.12.0-py2.py3-none-any.whl to /var/code/doron/pynvim/.eggs

Installed /var/code/doron/pynvim/.eggs/six-1.12.0-py3.7.egg
Searching for py>=1.5.0
Best match: py 1.8.0
Processing py-1.8.0-py3.7.egg

Using /var/code/doron/pynvim/.eggs/py-1.8.0-py3.7.egg
Searching for pluggy!=0.10,<1.0,>=0.9
Best match: pluggy 0.11.0
Processing pluggy-0.11.0-py3.7.egg

Using /var/code/doron/pynvim/.eggs/pluggy-0.11.0-py3.7.egg
Searching for more-itertools>=4.0.0
Best match: more-itertools 7.0.0
Processing more_itertools-7.0.0-py3.7.egg

Using /var/code/doron/pynvim/.eggs/more_itertools-7.0.0-py3.7.egg
Searching for attrs>=17.4.0
Best match: attrs 19.1.0
Processing attrs-19.1.0-py3.7.egg

Using /var/code/doron/pynvim/.eggs/attrs-19.1.0-py3.7.egg
Searching for atomicwrites>=1.0
Reading https://pypi.org/simple/atomicwrites/
Downloading https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl#sha256=03472c30eb2c5d1ba9227e4c2ca66ab8287fbfbbda3888aa93dc2e28fc6811b4
Best match: atomicwrites 1.3.0
Processing atomicwrites-1.3.0-py2.py3-none-any.whl
Installing atomicwrites-1.3.0-py2.py3-none-any.whl to /var/code/doron/pynvim/.eggs

Installed /var/code/doron/pynvim/.eggs/atomicwrites-1.3.0-py3.7.egg
running egg_info
writing pynvim.egg-info/PKG-INFO
writing dependency_links to pynvim.egg-info/dependency_links.txt
writing requirements to pynvim.egg-info/requires.txt
writing top-level names to pynvim.egg-info/top_level.txt
reading manifest file 'pynvim.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pynvim.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    zip_safe=False)
  File "/home/doron/.virtualenvs/pynvim/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/doron/.virtualenvs/pynvim/lib/python3.7/site-packages/setuptools/command/test.py", line 228, in run
    self.run_tests()
  File "/home/doron/.virtualenvs/pynvim/lib/python3.7/site-packages/setuptools/command/test.py", line 250, in run_tests
    exit=False,
  File "/usr/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.7/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.7/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib/python3.7/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.7/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.7/unittest/loader.py", line 406, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib/python3.7/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/home/doron/.virtualenvs/pynvim/lib/python3.7/site-packages/setuptools/command/test.py", line 54, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.7/unittest/loader.py", line 205, in loadTestsFromName
    test = obj()
TypeError: plugin() missing 1 required positional argument: 'cls'
```
</details>

**Comment by justinmk** [comment]
`python setup.py test` is not something tested by our CI. I guess it invokes the tests in a different way.


related but different: https://github.com/neovim/pynvim/issues/367
