### ISSUE TITLE
module greenlet not recognized

### ISSUE THREAD

**Issue by dongwangdw** [neovim/pynvim#503]
My OS: ubuntu 20.04
Python3: 3.9.5

I installed the module with: pip3 install pynvim
But module greenlet is missing.

Even I install this greenlet module I still have this module missing error.

```
python3 -m pip install pynvim
Requirement already satisfied: pynvim in /usr/lib/python3/dist-packages (0.4.1)

python3 -m pip install greenlet
Requirement already satisfied: greenlet in /usr/lib/python3/dist-packages (0.4.15)

>>> import pynvim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pynvim/__init__.py", line 11, in <module>
    from .msgpack_rpc import (ErrorResponse, child_session, socket_session,
  File "/usr/lib/python3/dist-packages/pynvim/msgpack_rpc/__init__.py", line 10, in <module>
    from .session import ErrorResponse, Session
  File "/usr/lib/python3/dist-packages/pynvim/msgpack_rpc/session.py", line 7, in <module>
    import greenlet
ModuleNotFoundError: No module named 'greenlet'

```

What have I missed here? Please help.

**Comment by Shougo** [comment]
Please see it.

https://github.com/gevent/gevent/issues/1207

Your installation seems broken.

**Comment by dongwangdw** [comment]
Yep, it is. I resolved it by upgrading th modules.
` pip3 install -U greenlet`

close this.
